Issue 11 age validation
Roger-Heathcote/spellingapp pull request #17
Opened 2021-05-29 10:58 UTC by SampathKumar27896

-Worked on age validation component to allow users to enter the valid age.

2021-06-01 12:06 UTC, Roger-Heathcote requested changes
Good stuff Sampath. Just the one comment and it's nothing important.

2021-06-01 12:06 UTC, Roger-Heathcote commented on src/components/AgeRange.js
> +    if (!isValidAge())
So instead of an if else statement maybe we could just have

```
    setWarning(!isValidAge())
```

2021-06-04 03:24 UTC, SampathKumar27896 commented
The changes are done as per the suggestion.

2021-06-07 11:40 UTC, Roger-Heathcote approved these changes

2021-06-07 11:40 UTC, merged